export let FETCH_QUIZES_START = 'FETCH_QUIZES_START'
export let FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS'
export let FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR'
export let FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'


export let QUIZ_SET_STATE = 'QUIZ_SET_STATE'
export let FINISH_QUIZ = 'FINISH_QUIZ'
export let QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION'

export let QUIZ_RETRY = 'QUIZ_RETRY'

export let CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION'
export let RESET_QUIZ_CREATION = 'RESET_QUIZ_CREATION'

export let AUTH_SUCCESS = 'AUTH_SUCCESS'
export let AUTH_LOGOUT = 'AUTH_LOGOUT'